### ISSUE TITLE
Notebook 07 - Milestone Project 1: Food Vision Big

### ISSUE THREAD

**Issue by abhi8893** [abhi8893/Tensorflow-tutorial-Daniel-Bourke#32]
Tasks:

- [x] Using Tensorflow Datasets to download and explore the data (A way to dump the data somewhere?)
- [x] Create preprocessing functions for our data
- [x] Batching and preparing datasets (datasets are prefetched and preprocessed faster)
- [x] Create modelling callbacks
- [x] Setting up mixed precision training (requires gpu compute capability > 7.0)
- [x] Build a feature extraction model (transfer learning)
- [x] Fine tune the feature extraction model 
- [x] Viewing the training results on TensorBoard
